name: Chart Repo PR Action
author: 'Red Hat CoP'
description: Automatically make a PR to an upstream chart repository
branding:
  icon: 'git-pull-request'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  auth_token:
    description: Token used for authentication to push to fork
    required: true
  fork_name:
    description: "Name of your Helm charts fork (ex: deweya/helm-charts)"
    required: true
  upstream_owner:
    description: "Owner of the upstream Helm charts repo (ex: redhat-cop)"
    required: true
  auth_user:
    description: Username used for authentication to push to fork. If blank, defaults to the user who triggered the action.
    required: false
  local_charts_dir:
    description: Charts directory name in local repo
    required: false
    default: charts
  upstream_charts_dir:
    description: Charts directory name in upstream repo
    required: false
    default: charts
  committer_name:
    description: The GitHub username to use as the committer name. If blank, defaults to the user who triggered the action.
    required: false
  committer_email:
    description: The email to use as the committer email
    required: false
    default: <>
  commit_message:
    description: Commit message to use when pushing to fork
    required: false
    default: Syncing local charts with upstream chart repo
  source_branch:
    description: New or existing branch the action should use as the source branch for the PR
    required: false
    default: feat/sync
  target_branch:
    description: Branch that the PR should target
    required: false
    default: master